{% set name = "fastreg" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastreg-{{ version }}.tar.gz
  sha256: 56d504d02cbff1dc55775bf40b317ab402cc89702d5a34882c5c70216381806f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - pandas
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - fastreg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/fastreg/
  summary: Fast sparse regressions
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - corentinlelannier
